# Generated by Django 3.1.4 on 2020-12-30 21:32

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_invoice_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, default=orders.models.Invoice.increment_invoice_number, max_length=500, null=True),
        ),
    ]
