# Generated by Django 3.1.4 on 2020-12-31 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201230_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='statsus',
            new_name='status',
        ),
    ]
